name: Repository 1 - REST API.
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run script
        run: echo "testing..."
